# export UID && docker-compose up
# http://localhost:8000/
# export UID && docker-compose exec recruitment_php /bin/sh
# export UID && docker-compose exec recruitment_node /bin/sh

version: '3.5'

services:
  recruitment_php:
    container_name: recruitment_php_dev
    build:
      context: config
      dockerfile: dockerfile-php
    volumes: [".:/app"]
    user: ${UID}
    working_dir: /app
    networks: [recruitment]

  recruitment_node:
    container_name: recruitment_node_dev
    image: node:16-alpine
    tty: true
    volumes: [ ".:/app" ]
    working_dir: /app

  recruitment_http:
    container_name: recruitment_http_dev
    image: nginx:1
    depends_on: [recruitment_php]
    volumes: [".:/app", "./config/docker-nginx.conf:/etc/nginx/conf.d/default.conf"]
    ports: ["8000:80"]
    networks: [recruitment]

networks:
  recruitment:
    name: recruitment_dev
    #external:
    #  name: neucore_dev
